apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rivoll/projet-k/
    targetRevision: HEAD
    chart: applications-charts/myapp
    helm:
      valueFiles:
        - applications-charts/myapp/dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

valueFiles: applications-charts/myapp/dev-values.yaml