apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rivoll/projet-k/
    targetRevision: HEAD
    path: applications-charts/myapp
    helm:
      valueFiles:
      - staging-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

valueFiles: staging-values.yaml