apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: "160885295462.dkr.ecr.eu-west-3.amazonaws.com/dev/myapp:{{.Values.tag}}"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-secret
