apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 160885295462.dkr.ecr.eu-west-3.amazonaws.com/dev/myapp:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ecr-secret
