apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{.Values.app.name}}-{{.Values.env}}
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{.Values.app.name}}-{{.Values.env}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}-{{.Values.env}}
    spec:
      containers:
        - name: {{.Values.app.name}}-{{.Values.env}}
          image: "160885295462.dkr.ecr.eu-west-3.amazonaws.com/dev/myapp:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: ecr-secret
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause:
          manual: true  # Manual approval step to control when the rollout proceeds
      - setWeight: 50
      - pause:
          manual: true
      - setWeight: 75
      - pause:
          manual: true
      - setWeight: 100
      - pause:
          manual: true