apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{.Values.app.name}}-{{.Values.env}}
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{.Values.app.name}}-{{.Values.env}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}-{{.Values.env}}
    spec:
      containers:
        - name: myapp
          image: "160885295462.dkr.ecr.eu-west-3.amazonaws.com/dev/myapp:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

      imagePullSecrets:
      - name: ecr-secret
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause:
            duration: 1m
        - setWeight: 50
        - pause:
            duration: 1m
        - setWeight: 75
        - pause:
            duration: 1m
        - setWeight: 100
        - pause:
            duration: 1