apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Rivoll/projet-k/
      path: applications-charts/myApp
      targetRevision: HEAD
      helm:
        valueFiles:
        - dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true