{{- if not .Values.server.statefulSet.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prometheus.server.fullname" . }}
  namespace: {{ include "prometheus.namespace" . }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.server.deploymentAnnotations | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus.server.matchLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.server.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.server.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "prometheus.server.labels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.server.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ template "prometheus.serviceAccountName.server" . }}
      {{- if .Values.server.automountServiceAccountToken }}
      automountServiceAccountToken: {{ .Values.server.automountServiceAccountToken }}
      {{- end }}
      containers:
      - name: {{ template "prometheus.name" . }}-server
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
        args:
          - --config.file={{ .Values.server.configPath }}
          - --storage.tsdb.path={{ if .Values.server.storagePath }}{{ .Values.server.storagePath }}{{ else }}{{ .Values.server.persistentVolume.mountPath }}{{ end }}
          - --web.route-prefix={{ .Values.server.prefixURL }}
          - --web.external-url={{ .Values.server.baseURL }}
          - --storage.tsdb.retention.time={{ .Values.server.retention }}
          {{- range $key, $value := .Values.server.extraArgs }}
          - --{{ $key }}={{ $value }}
          {{- end }}
        ports:
        - containerPort: 9090
          name: web
        readinessProbe:
          httpGet:
            path: {{ .Values.server.prefixURL }}/-/ready
            port: 9090
          initialDelaySeconds: {{ .Values.server.readinessProbeInitialDelay }}
          periodSeconds: {{ .Values.server.readinessProbePeriodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.server.prefixURL }}/-/healthy
            port: 9090
          initialDelaySeconds: {{ .Values.server.livenessProbeInitialDelay }}
          periodSeconds: {{ .Values.server.livenessProbePeriodSeconds }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: storage-volume
          mountPath: {{ .Values.server.persistentVolume.mountPath }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "prometheus.server.fullname" . }}
      - name: storage-volume
        persistentVolumeClaim:
          claimName: {{ template "prometheus.server.fullname" . }}
{{- end }}
