{{- if .Values.server.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "prometheus.server.fullname" . }}-ingress
  namespace: {{ include "prometheus.namespace" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- toYaml .Values.server.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  {{- if and .Values.server.ingress.hosts (gt (len .Values.server.ingress.hosts) 0) }}
  rules:
    {{- range .Values.server.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.server.ingress.path }}
            pathType: {{ $.Values.server.ingress.pathType }}
            backend:
              service:
                name: {{ template "prometheus.server.fullname" $ }}
                port:
                  number: {{ $.Values.server.service.servicePort }}
    {{- end }}
  {{- else }}
  defaultBackend:
    service:
      name: {{ template "prometheus.server.fullname" . }}
      port:
        number: {{ .Values.server.service.servicePort }}
  {{- end }}
{{- end }}
