pipeline {
    agent {
        kubernetes {
            yaml """
        apiVersion: v1
        kind: Pod
        metadata:
          labels:
            some-label: jenkins-agent
        spec:
          containers:
          - name: jnlp
            image: jenkins/inbound-agent:latest
            tty: true
          - name: docker
            image: docker:20.10
            command:
            - cat
            tty: true
        """
        }
    }


    environment {
        AWS_DEFAULT_REGION = 'eu-west-3' 
        ECR_REPO = "160885295462.dkr.ecr.eu-west-3.amazonaws.com/myapp"
        IMAGE_TAG = "${BUILD_NUMBER}"  
        K8S_MANIFESTS_REPO = 'git@github.com:Rivoll/projet-k.git' // Use SSH instead of HTTPS
        GIT_USER_EMAIL = credentials('pkeita@student.42.fr') // Store email in Jenkins Credentials
    }

    stages {
        stage('Build and Test') {
            steps {
                script {
                    // Build the Docker image
                    sh 'docker build -t ${ECR_REPO}:${IMAGE_TAG} .'
                    // Run tests
                    sh 'run-test.sh'  
                }
            }
        }

        stage('Push Image to ECR') {
            steps {
                withAWS(credentials: 'aws-credentials-id', region: "${AWS_DEFAULT_REGION}") {
                    script {
                        // Authenticate with ECR
                        sh 'aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}'
                        // Push the Docker image to ECR
                        sh 'docker push ${ECR_REPO}:${IMAGE_TAG}'
                    }
                }
            }
        }

        stage('Update Kubernetes Manifests') {
            steps {
                sshagent(['github-ssh-key']) {
                    sh """
                    git clone ${K8S_MANIFESTS_REPO} k8s-manifests
                    cd k8s-manifests/applications-charts/myapp
                    # Update image tag in values.yaml
                    sed -i 's|tag: .*|tag: ${IMAGE_TAG}|' staging-values.yaml
                    # Commit changes
                    git config user.email "${GIT_USER_EMAIL}"
                    git config user.name "Jenkins"
                    git add staging-values.yaml
                    git commit -m "Update image tag to ${IMAGE_TAG}"
                    git push origin main
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'CI pipeline succeeded! Image pushed and Kubernetes manifests updated.'
        }
        failure {
            echo 'CI pipeline failed.'
        }
    }
}
