apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-appset
spec:
  generators:
    - git:
        repoURL: "https://github.com/Rivoll/projet-k"
        revision: main
        directories:
          - path: "applications-charts/*"
  template:
    metadata:
      name: "{{path.basename}}" # App name = directory name
    spec:
      project: default
      source:
        repoURL: "git@github.com:Rivoll/projet-k.git"
        targetRevision: main
        path: "applications-charts/{{path.basename}}"
        helm:
          valueFiles:
            - "values.yaml"
            - "{{path.basename}}-values.yaml"  # Dynamically load values from `myapp-values.yaml`
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
