apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Rivoll/projet-k # Replace with your repository
        revision: HEAD
        files:
          - path: "argocd-apps/helm-apps/*.yaml" # Path to your YAML files
  template:
    metadata:
      name: "{{metadata.name}}" # Dynamic name based on the YAML file
    spec:
      project: default
      source:
        repoURL: "{{spec.source.repoURL}}"
        targetRevision: "{{spec.source.targetRevision}}"
        # Conditional logic for 'path' or 'chart'
        {{- if .spec.source.path }}
        path: "{{.spec.source.path}}" # For Git-based Helm charts
        {{- else if .spec.source.chart }}
        chart: "{{.spec.source.chart}}" # For Helm repository-based charts
        {{- end }}
        helm:
          valueFiles:
            - "{{.spec.source.helm.valueFiles}}" # Dynamic value files
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{.spec.destination.namespace}}" # Dynamic namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true