apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/Rivoll/projet-k.git
        revision: main
        files:
          - path: applications-charts/*/values/*  # Watch all values files in all apps
  template:
    metadata:
      name: "{{path[1]}}-{{path.filenameNormalized}}"  # appname-env (e.g., myapp-staging)
    spec:
      project: default
      source:
        repoURL: https://github.com/Rivoll/projet-k.git
        targetRevision: main
        path: applications-charts/{{path[1]}}  # Path to each Helm chart
        helm:
          valueFiles:
            - "values/{{path.filenameNormalized}}"  # Use matching values file (e.g., staging.yaml)
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path[1]}}-{{path.filenameNormalized}}"  # appname-env
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  retry:
    limit: 3  # Retry 3 times if deployment fails
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
