apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Rivoll/projet-k # Remplacer par votre propre dépôt
        revision: HEAD
        files:
          - path: "applications-kustomize/*/kustomization.yaml" # Indiquez ici le chemin vers vos fichiers YAML Kustomize
  template:
    metadata:
      name: "{{ path.basename }}" # Nom dynamique basé sur le fichier YAML
    spec:
      project: default
      source:
        repoURL: https://github.com/Rivoll/projet-k
        targetRevision: main
        path: "applications-kustomize/{{ path.basename }}/"
        kustomize:
          namePrefix: ""
      destination:
        server: "https://kubernetes.default.svc"
        namespace: prod # Définir le namespace de déploiement
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
