apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: plain-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Rivoll/projet-k # Remplacer par votre propre dépôt
        revision: HEAD
        files:
          - path: "argocd-apps/plain-apps/*.yaml" # Indiquez ici le chemin vers vos fichiers YAML Helm
  template:
    metadata:
      name: "{{metadata.name}}" # Nom dynamique basé sur le fichier YAML
    spec:
      project: default
      source:
        repoURL: "{{spec.source.repoURL}}"
        targetRevision: "{{spec.source.targetRevision}}"
        path: "{{spec.source.path}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{spec.destination.namespace}}" # Définissez ici le namespace de déploiement
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
