apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app.name}}
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      containers:
      - name: {{.Values.app.name}}
        image: 160885295462.dkr.ecr.eu-west-3.amazonaws.com/dev/myapp:maga
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-secret
