apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: myapp2
        image: 160885295462.dkr.ecr.eu-west-3.amazonaws.com/dev/myapp:maga
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ecr-secret
