apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    - repoURL: https://charts.jenkins.io
      targetRevision: '*'
      chart: jenkins
      helm:
        valueFiles:
        - $values/applications-charts/jenkins/jenkins-values.yaml
    - repoURL: https://github.com/Rivoll/projet-k
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

repoURL: https://github.com/Rivoll/projet-k/