apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.name}}-{{.Values.env}}
  namespace: {{.Values.env}}
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/app-root: "/myapp-staging/"
spec:
  ingressClassName: {{.Values.ingressClassName}}
  rules:
    - http:
        paths:
          - path: /myapp-{{.Values.env}}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: myapp-{{.Values.env}}-svc
                port:
                  number: 80
          - path: /myapp2-{{.Values.env}}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: myapp2-{{.Values.env}}-svc
                port:
                  number: 80