apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-{{.Values.env}}-svc
  namespace: {{.Values.env}}
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  type: NodePort  # ✅ Expose externally
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{.Values.NodePort}}  # ✅ Correct NodePort
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443