apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-ingress-class
subjects:
- kind: ServiceAccount
  name: default
  namespace: ingress-nginx
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Vous pouvez ajuster le rôle si nécessaire pour des permissions plus limitées
  apiGroup: rbac.authorization.k8s.io
