---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-ingress-controller
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
    spec:
      containers:
        - name: nginx-ingress-controller
          image: k8s.gcr.io/ingress-nginx/controller:v1.7.0  # Ensure this image is correct
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service
  namespace: ingress-nginx
spec:
  selector:
    app: nginx-ingress-controller
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100  # 🔥 Expose on NodePort 30100
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: NodePort  # 🔥 Set service type to NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # 🔥 Ensures correct path handling
spec:
  rules:
    - http:
        paths:
          - path: /myapp-dev
            pathType: Prefix
            backend:
              service:
                name: myapp-dev-service  # Match the service of your app
                port:
                  number: 80
          - path: /myapp-staging
            pathType: Prefix
            backend:
              service:
                name: myapp-staging-service
                port:
                  number: 80
          - path: /myapp2-dev
            pathType: Prefix
            backend:
              service:
                name: myapp2-dev-service
                port:
                  number: 80
          - path: /myapp2-staging
            pathType: Prefix
            backend:
              service:
                name: myapp2-staging-service
                port:
                  number: 80
  ingressClassName: nginx  # 🔥 Ensure you are using the correct Ingress controller
