apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress-controller
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
    spec:
      containers:
        - name: nginx-ingress-controller
          image: k8s.gcr.io/ingress-nginx/controller:v1.7.0
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service
  namespace: ingress-nginx
spec:
  selector:
    app: nginx-ingress-controller
  ports:
    - name: http  # Nom pour le port 80
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https  # Nom pour le port 443
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
