apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # ✅ Ensure correct path forwarding
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /myapp-dev  # ✅ No regex
            pathType: Prefix
            backend:
              service:
                name: myapp-dev-svc
                port:
                  number: 80
          - path: /myapp-staging  # ✅ No regex
            pathType: Prefix
            backend:
              service:
                name: myapp-staging-svc
                port:
                  number: 80
          - path: /myapp-prod  # ✅ No regex
            pathType: Prefix
            backend:
              service:
                name: myapp-prod-svc
                port:
                  number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-service
  namespace: ingress-nginx
spec:
  selector:
    app: nginx-ingress-controller
  type: NodePort  # ✅ Expose externally
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100  # ✅ Correct NodePort
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
