apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-reader
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oidc-reader
rules:
  - apiGroups: [""]
    resources: ["openidconfiguration"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-reader-binding
subjects:
  - kind: ServiceAccount
    name: oidc-reader
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: oidc-reader
  apiGroup: rbac.authorization.k8s.io
