apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc2
  namespace: jenkins
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
