apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"component":"cloud-controller-manager"},"name":"aws-cloud-controller-manager","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"component":"cloud-controller-manager"}},"template":{"metadata":{"labels":{"component":"cloud-controller-manager"}},"spec":{"containers":[{"args":["--cloud-provider=aws","--v=2"],"image":"gcr.io/k8s-staging-cloud-provider-aws/cloud-controller-manager:v1.27.0","name":"aws-cloud-controller-manager","resources":{"requests":{"cpu":"200m","memory":"100Mi"}}}],"serviceAccountName":"cloud-controller-manager","tolerations":[{"effect":"NoSchedule","key":"node.cloudprovider.kubernetes.io/uninitialized","value":"true"}]}}}}
  creationTimestamp: "2025-01-31T00:30:19Z"
  generation: 4
  labels:
    component: cloud-controller-manager
  name: aws-cloud-controller-manager
  namespace: kube-system
  resourceVersion: "1229210"
  uid: 52c2cd95-3d58-49dd-bf9e-625d6bc0ca7d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: cloud-controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-01-31T00:42:46Z"
      creationTimestamp: null
      labels:
        component: cloud-controller-manager
    spec:
      containers:
      - args:
        - --cloud-provider=aws
        - --v=2
        image: registry.k8s.io/provider-aws/cloud-controller-manager:v1.29.0
        imagePullPolicy: IfNotPresent
        name: aws-cloud-controller-manager
        resources:
          requests:
            cpu: 200m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cloud-controller-manager
      serviceAccountName: cloud-controller-manager
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
status:
  conditions:
  - lastTransitionTime: "2025-01-31T00:30:19Z"
    lastUpdateTime: "2025-01-31T00:42:48Z"
    message: ReplicaSet "aws-cloud-controller-manager-79f9ddcff5" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-01-31T03:30:46Z"
    lastUpdateTime: "2025-01-31T03:30:46Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 4
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
