{{- if .Values.ingress.enabled -}}
{{- $fullName := include "grafana.fullname" . -}}
apiVersion: {{ include "grafana.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ include "grafana.namespace" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:

  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name:  {{ include "grafana.fullname" . }}
            port:
              number: 80
{{- end }}            
