{{- if .Values.ingress.enabled -}}
{{- $fullName := include "grafana.fullname" . -}}
apiVersion: {{ include "grafana.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ include "grafana.namespace" . }}
  annotations: {}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name:  {{ include "grafana.fullname" . }}
            port:
              number: 80