---
- name: Setup Kubernetes Worker Node
  hosts: admin
  gather_facts: yes
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Turn off swap temporarily
      command: swapoff -a

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies for containerd
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present 

    - name: Download Docker GPG key
      get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Add Docker GPG key to apt
      command: >
        apt-key add /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
        state: present
        create: yes

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install containerd.io
      apt:
        name: containerd.io
        state: present
