---
- name: Install AWS CLI
  hosts: main
  become: true

  tasks:
    - name: Download AWS CLI installer
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: /tmp/awscliv2.zip

    - name: Install unzip if not already installed
      apt:
        name: unzip
        state: present

    - name: Extract AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes

    - name: Run AWS CLI installer
      command: /tmp/aws/install

    - name: Verify AWS CLI installation
      command: aws --version
      register: aws_output
      ignore_errors: yes

    - name: Print AWS CLI version
      debug:
        msg: "{{ aws_output.stdout }}"
