---
- name: Install containerd
  hosts: admin
  become: yes
  tasks:
    - name: Remove all Docker-related repository entries
      shell: >
        find /etc/apt/sources.list.d/ -type f -name "*.list" -exec grep -l 'download.docker.com' {} \; |
        xargs rm -f

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies for containerd
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Download Docker GPG key
      get_url:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        create: yes

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install containerd.io
      apt:
        name: containerd.io
        state: present

    - name: Create default containerd configuration file
      command: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Restart containerd service
      service:
        name: containerd
        state: restarted
        enabled: yes
