controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: lts
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  serviceType: LoadBalancer
  ingress:
    enabled: false
  admin:
    username: admin
    password: admin123

persistence:
  enabled: true
  storageClass: ""
  size: 8Gi
