apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 80  # Port exposé dans le cluster
      targetPort: 80  # Port sur lequel le conteneur écoute
      nodePort: 30080  # Port exposé sur chaque nœud du cluster
  type: NodePort